name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reserve/pom.xml
          mvn clean package -f ./clean/pom.xml
          mvn clean package -f ./hotelRoom/pom.xml
          mvn clean package -f ./customerCenter/pom.xml

      - name: Docker Build and push for Reserve
        uses: docker/build-push-action@v4
        with:
          context: ./reserve
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reserve:latest
            ghcr.io/${{ github.repository }}/reserve:${{ github.ref_name }}
            
      - name: Docker Build and push for Clean
        uses: docker/build-push-action@v4
        with:
          context: ./clean
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/clean:latest
            ghcr.io/${{ github.repository }}/clean:${{ github.ref_name }}
            
      - name: Docker Build and push for HotelRoom
        uses: docker/build-push-action@v4
        with:
          context: ./hotelRoom
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hotelroom:latest
            ghcr.io/${{ github.repository }}/hotelroom:${{ github.ref_name }}
            
      - name: Docker Build and push for CustomerCenter
        uses: docker/build-push-action@v4
        with:
          context: ./customerCenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customercenter:latest
            ghcr.io/${{ github.repository }}/customercenter:${{ github.ref_name }}
            
