server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: point
          uri: http://localhost:8082
          predicates:
            - Path=/points/**, 
        - id: reserve
          uri: http://localhost:8083
          predicates:
            - Path=/reserves/**, 
        - id: notify
          uri: http://localhost:8084
          predicates:
            - Path=/notifies/**, 
        - id: hotelRoom
          uri: http://localhost:8085
          predicates:
            - Path=/hotelRooms/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/reserves/**, 
        - id: notify
          uri: http://notify:8080
          predicates:
            - Path=/notifies/**, 
        - id: hotelRoom
          uri: http://hotelRoom:8080
          predicates:
            - Path=/hotelRooms/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
