---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserve
  labels:
    app: reserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reserve
  template:
    metadata:
      labels:
        app: reserve
    spec:
      containers:
        - name: reserve
          image: username/reserve:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean
  labels:
    app: clean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clean
  template:
    metadata:
      labels:
        app: clean
    spec:
      containers:
        - name: clean
          image: username/clean:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelRoom
  labels:
    app: hotelRoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotelRoom
  template:
    metadata:
      labels:
        app: hotelRoom
    spec:
      containers:
        - name: hotelRoom
          image: username/hotelRoom:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerCenter
  labels:
    app: customerCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerCenter
  template:
    metadata:
      labels:
        app: customerCenter
    spec:
      containers:
        - name: customerCenter
          image: username/customerCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: reserve
  labels:
    app: reserve
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reserve


---


apiVersion: v1
kind: Service
metadata:
  name: clean
  labels:
    app: clean
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: clean


---


apiVersion: v1
kind: Service
metadata:
  name: hotelRoom
  labels:
    app: hotelRoom
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hotelRoom


---


apiVersion: v1
kind: Service
metadata:
  name: customerCenter
  labels:
    app: customerCenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customerCenter

